### ISSUE TITLE
Think of appropriate permissions and restrict REST HTTP endpoints

### ISSUE THREAD

**Issue by NC5324** [NC5324/st-mssn#38]
1. Add permissions like the three already defined in [UserPermission enum](/NC5324/st-mssn/tree/master/src/main/java/com/st/mssn/security/UserPermission.java)
2. Restrict REST HTTP endpoints by adding @AllowPermissions decorator (refer to [FilterResource](/NC5324/st-mssn/tree/master/src/main/java/com/st/mssn/web/rest/FilterResource.java))

**Comment by Moomchi** [comment]
Done with  #53
